/**
 * Album Photos Data - Auto-generated from R2
 * 
 * This file is generated by: node scripts/sync-photos.js
 * 
 * To update: Upload images to R2, then run the sync script.
 * To customize: Edit width/height/isHDR after generation.
 * 
 * Last synced: 2025-12-27T05:38:04.406Z
 */

import { R2Photo } from './r2';

export const albumPhotos: Record<string, R2Photo[]> = {
  // ---------------------------------------------------------------------------
  // Lisbon
  // ---------------------------------------------------------------------------
  'lisbon': [
    { filename: 'IMG_4982.jpeg', title: 'IMG 4982', width: 1920, height: 1280 },
    { filename: 'lisbon-streets-1.jpeg', title: 'Lisbon Streets 1', width: 1920, height: 1280 },
    { filename: 'lisbon-streets-2.jpeg', title: 'Lisbon Streets 2', width: 1920, height: 1280 },
  ],

  // ---------------------------------------------------------------------------
  // Porto
  // ---------------------------------------------------------------------------
  'porto': [
    { filename: 'porto-1.jpeg', title: 'Porto 1', width: 1920, height: 1280 },
    { filename: 'porto-2.jpeg', title: 'Porto 2', width: 1920, height: 1280 },
    { filename: 'porto-3.jpeg', title: 'Porto 3', width: 1920, height: 1280 },
  ],

  // ---------------------------------------------------------------------------
  // Prague
  // ---------------------------------------------------------------------------
  'prague': [
    { filename: 'prague-1.jpeg', title: 'Prague 1', width: 1920, height: 1280 },
  ],

  // ---------------------------------------------------------------------------
  // Switzerland
  // ---------------------------------------------------------------------------
  'switzerland': [
    { filename: 'switzerland-1.jpeg', title: 'Switzerland 1', width: 1920, height: 1280 },
    { filename: 'switzerland-2.jpeg', title: 'Switzerland 2', width: 1920, height: 1280 },
    { filename: 'switzerland-3.jpeg', title: 'Switzerland 3', width: 1920, height: 1280 },
  ],

  // ---------------------------------------------------------------------------
  // Venice
  // ---------------------------------------------------------------------------
  'venice': [
    { filename: 'venice-1.jpeg', title: 'Venice 1', width: 1920, height: 1280 },
  ],

};
